/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_max_ermakov_smoketunnel_SmokeNDKManager */

#ifndef _Included_com_example_max_ermakov_smoketunnel_SmokeNDKManager
#define _Included_com_example_max_ermakov_smoketunnel_SmokeNDKManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_max_ermakov_smoketunnel_SmokeNDKManager
 * Method:    init
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_max_1ermakov_smoketunnel_SmokeNDKManager_init
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
