/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_max_ermakov_smoketunnel_SmokeNDKManager */

#ifndef _Included_com_example_max_ermakov_smoketunnel_SmokeNDKManager
#define _Included_com_example_max_ermakov_smoketunnel_SmokeNDKManager
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
